#pragma once
// TODO(Codex): Implement small Vec3/Mat3 with only what we need (dot, cross, normalize).
struct Vec3 { double x,y,z; /* ... */ };
inline double dot(const Vec3&, const Vec3&); // ...
inline Vec3 cross(const Vec3&, const Vec3&); // ...
